services:
  api:
    build:
      context: ./api
    container_name: playoffarena_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: playoffarena_nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped
      
  db:
    image: postgres:16-alpine
    container_name: playoffarena_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=playoff_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=playoffarena
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: